### ISSUE TITLE
ebigcomic4 作品ページへのリンクページを作成する

### ISSUE THREAD

**Issue by opst-fujimoto** [opst-fujimoto/my-site-github#135]
## 目的
site:www.ebigcomic4.jp/title/　へのindex数を増やしたく、被リンクのページ（サイト）を作る

## landing page

https://opst-fujimoto.github.io/my-site-github/ebigcomic4/

## 作業内容

- `Portfolio section` に　作品のポートフォリオ（作品名、作家名、作品画像mainvisual）を記載する
- `Portfolio section` の `a` タグに https://www.ebigcomic4.jp/title/xxx のURLを記載する
- `History section` に　作品の配信開始日(1話の配信開始日）、作品名、作家名、作品の概要、作品画像mainvisualを記載する
- `History section` の `a` タグに https://www.ebigcomic4.jp/title/xxx のURLを記載する

## 作品一覧

以下の順で作品を随時、追加していくが、まずは、1作品目を記載し、表示内容を確認する

- [x] 太陽の黙示録
- [x] ペンギン日和
- [x] 報復刑
- [x] 肉の誘惑
- [x] Sエス
- [x] ギャラリーフェイク
- [x] ガンダム
- [x] 美味しんぼ
- [x] ラストニュース /title/119433
- [x] HOTEL /title/107368
- [x] ぼくの忘れ物 /369313
- [x] 銀十字 /title/340052
- [x] あんどーなつ /title/123261
- [x] 闇金ウシジマくん /title/118166
- [x] ラストイニング /title/125996
- [x] HEAT /title/109896
- [x] 岳 /title/120619

- [x] 風の大地 /title/117105
- [x] 土佐の一本釣り /title/108636

**Comment by opst-fujimoto** [comment]
@opst-fuukei

**Comment by opst-fujimoto** [comment]
@matsuo-y 

- [ ] ギャラリーフェイク /title/119193
- [ ] ガンダム /title/340051
- [ ] 美味しんぼ /title/113091

を追加してください。ブランチは　#135-ebigcomic-landing-page　のままで、追加でPRを作成してください。

**Comment by opst-fujimoto** [comment]
@opsttan 

- [ ] ラストニュース /title/119433
- [ ] HOTEL /title/107368
- [ ] ぼくの忘れ物 /369313

を追加してください。ブランチは　#135-ebigcomic-landing-page　のままで、追加でPRを作成してください。

**Comment by opst-fujimoto** [comment]
@gonomk 

- [ ] 銀十字 /title/340052
- [ ] あんどーなつ /title/123261

を追加してください。ブランチは　#135-ebigcomic-landing-page　のままで、追加でPRを作成してください。

Escape, Dreamsは削除してください

**Comment by opst-fujimoto** [comment]
@matsuo-y 

- [ ] 闇金ウシジマくん /title/118166
- [ ] ラストイニング /title/125996

を追加してください。ブランチは　#135-ebigcomic-landing-page　のままで、追加でPRを作成してください。

**Comment by opst-fujimoto** [comment]
@opst-ueda 

- [ ] HEAT /title/109896
- [ ] 岳 /title/120619

を追加してください。ブランチは　#135-ebigcomic-landing-page　のままで、追加でPRを作成してください。

**Comment by opst-fujimoto** [comment]
@opst-ueda 

- [ ] 風の大地 /title/117105
- [ ] 土佐の一本釣り /title/108636

を追加してください。ブランチは　#135-ebigcomic-landing-page　のままで、追加でPRを作成してください。

**Comment by opst-fujimoto** [comment]
@opst-ueda  風の大地と土佐の一本釣りも、今日おわらせておきたい

**Comment by opst-ueda** [comment]
@opst-fujimoto 見落としてました、すみません。今から対応します

**Comment by opst-ueda** [comment]
@opst-fujimoto 譚さんの対応と被りそうなので、やっぱりもう少しあとに着手します

**Comment by opst-fujimoto** [comment]
作品数の切りがいいので、これでおわりにします
