### ISSUE TITLE
2016.10.03 conflict morning

### ISSUE THREAD

**Issue by gonomk** [opst-fujimoto/my-site-github#160]
今日の朝ごはんを以下のサイトで公開できる

コミットメッセージは、`fix` を記載しないようにし、誰の朝食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の朝食かがわかる文言にする
PRのアサインは、以下のとおり
上田→譚→中村→上田
ex.) 上田が作成したPRは、譚にアサインして、譚がコメントおよびmergeする

本番環境：　https://opst-fujimoto.github.io/my-site-github/breakfast/201610.html

- [ ] 上田
- [ ] 譚
- [x] 中村

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://production-my-site-pr-{N}.herokuapp.com/

**Comment by opstnakamura** [comment]
10月分のファイル追加してみました。

**Comment by gonomk** [comment]
@opstnakamura ありがとうございます。

**Comment by gonomk** [comment]
@takakura-s @opst-ueda @opsttan 本日の朝食を追加してください。よろしくお願いします。

**Comment by gonomk** [comment]
高倉さんは終日席にいらっしゃらないとのことでしたので、本日は対象外とさせていただきました。フローも変更してありますので、よろしくお願いします。

**Comment by gonomk** [comment]
昨日（10/3）は上田さん、譚さんもお忙しいようでしたのでクローズしたいと思います。
10/4分からよろしくお願いします。
