### ISSUE TITLE
2016.10.xx stagingからmasterにマージして、release

### ISSUE THREAD

**Issue by gonomk** [opst-fujimoto/my-site-github#201]
## 関連チケット
- connect #xxx 

## マージ基準
- [ ] 本日の朝食がorigin/stagingに反映されていること
- [ ] 本日の昼食がorigin/stagingに反映されていること

https://staging-my-site-github.herokuapp.com/breakfast/201610.html
https://staging-my-site-github.herokuapp.com/lunch/201610.html
※origin/stagingのブランチは消さないこと

マージ後は、GitHubでrelease/tagの設定をおこなうこと
https://github.com/opst-fujimoto/my-site-github/releases

**Comment by opst-fujimoto** [comment]
release/tag の作業内容も記載しておいてください

**Comment by matsuo-y** [comment]
作業用に発行したissueにconnectしてマージをするようになったため、こちらはクローズします。
