### ISSUE TITLE
2016.10.07 stagingからmasterにマージして、release

### ISSUE THREAD

**Issue by gonomk** [opst-fujimoto/my-site-github#230]
## 関連チケット
- connect #219 
- connect #220

## マージ基準
- [x] 本日の朝食がorigin/stagingに反映されていること
- [x] 本日の昼食がorigin/stagingに反映されていること

https://staging-my-site-github.herokuapp.com/breakfast/201610.html
https://staging-my-site-github.herokuapp.com/lunch/201610.html
※origin/stagingのブランチは消さないこと

マージ後は、GitHubでrelease/tagの設定をおこなうこと
https://github.com/opst-fujimoto/my-site-github/releases

**Comment by gonomk** [comment]
<img src="https://cloud.githubusercontent.com/assets/21594803/19185719/defdcdc8-8cbd-11e6-9db6-36abd805a564.png" wdth="320px">

リリースしましたので、クローズします。

**Comment by opst-fujimoto** [comment]
v1.3とv1.2が、同じcommit idを指しているので、やり直し

**Comment by gonomk** [comment]
すみません、releaseは削除できてもtagは削除できなさそうだったのでいつもと違うtag名にしました。

<img src="https://cloud.githubusercontent.com/assets/21594803/19186186/05f305c2-8cc0-11e6-9c6c-92bfbfa50f24.png">
