### ISSUE TITLE
tag v1.3を削除する

### ISSUE THREAD

**Issue by opst-fujimoto** [opst-fujimoto/my-site-github#233]
## 作業内容

- https://github.com/opst-fujimoto/my-site-github/releases/tag/v1.3 を削除する

## 判定基準

- [x] https://github.com/opst-fujimoto/my-site-github/releases/tag/v1.3 にアクセスできない（削除されている）

**Comment by gonomk** [comment]
先に誤って作成したv1.3のタグを削除し、
改めてv1.3.1をv1.3に変更したため下記URLにアクセスできる状態となっています。
※紐づいているコミットIDは変わっています。
https://github.com/opst-fujimoto/my-site-github/releases/tag/v1.3

**Comment by opst-fujimoto** [comment]
commit IDを変更できたね。
今後のために、作業手順を残しておいて下さい。

@gonomk

**Comment by gonomk** [comment]
## 作業手順
- github上で、codeタブ > release > tag の順に画面を開き、削除対象のtagのリンクを選択する
<img src="https://cloud.githubusercontent.com/assets/21594803/19256492/748ecb12-8fa2-11e6-9af6-167d56d4bb17.png" width="320px">
- 遷移したタグの詳細画面にて右上の「delete」ボタンを押下する
<img src="https://cloud.githubusercontent.com/assets/21594803/19256528/c211054e-8fa2-11e6-8a18-831eb2afc706.png" width="320px">
- 削除したタグが codeタブ > release > tag の一覧に表示されていないことを確認する

**Comment by opst-fujimoto** [comment]
@gonomk 

``` shell
git tag -l
```

してみて

**Comment by gonomk** [comment]
まだv1.3.1がいました・・・。ということはv1.3自体も以前のままなのでしょうか。
調べてみます。

**Comment by gonomk** [comment]
@here 

リモートのタグを削除したらローカルのタグも別途削除しなくてはならないようです。
参考URL↓
http://qiita.com/ngyuki/items/ca7bed067d7e538fd0cd

**Comment by opst-fujimoto** [comment]
タグの挙動について、各自、把握しておいてください。
次の順で、回覧して、closeします

松尾 -> 上田 -> 譚 -> 中村 -> 高倉 -> 土井 -> 姜 -> 藤本

回覧した人は、その旨、コメントを残してください　@matsuo-y

**Comment by matsuo-y** [comment]
ローカルのタグの件は郷野さんと一緒に確認しました。

**Comment by opst-fujimoto** [comment]
次、　@opst-ueda

**Comment by opst-ueda** [comment]
みましたー、次は譚さん！
@opsttan

**Comment by opsttan** [comment]
見ました。次は中村さん
@opstnakamura

**Comment by opstnakamura** [comment]
見ました。

**Comment by takakura-s** [comment]
見ました。
@opst-D-Take

**Comment by opst-D-Take** [comment]
見ました。姜さん、お願いします。
@kan

**Comment by jiangheqing** [comment]
確認しました。@opst-fujimoto

余談ですが、上記に書いてある　@kan をクリックしたら。。

**Comment by kan** [comment]
こんにちは、急にmentionが飛んできてびっくりしたのですが、恐らく間違えて入力された感じですかね?

**Comment by jiangheqing** [comment]
こんにちは、間違えてしまいました。 申し訳ありません。

**Comment by opst-D-Take** [comment]
失礼しました。

**Comment by jiangheqing** [comment]
こちらこそ、失礼いたしました。

**Comment by opst-fujimoto** [comment]
close
