### ISSUE TITLE
/ebigcomic4/index.html において、不要なhtm/js/cssを削除する

### ISSUE THREAD

**Issue by opst-fujimoto** [opst-fujimoto/my-site-github#234]
## 作業内容

- 2016.10.11 9:00 時点で使用してないhtml内のDOM, js, css を調査し、削除する

**Comment by opsttan** [comment]
二つ質問させてください。
①PORTFOLIOの作品のサムネール、マウスオンの時表示された「＋」マック必要ですか？
②GTMのタグありますが、必要ですか？

**Comment by opst-fujimoto** [comment]
①「＋」マークは、残していても、なくしてもよいです。「＋」マーククリック時の挙動のために残っているDOMは不要です。
②GTMのタグは必要です、みなが、google analyticsを参照できるように、あえて追加しました　#138 #140

**Comment by opst-fujimoto** [comment]
![LGTM](https://lgtm.in/p/IoXMmT6hq)

**Comment by opsttan** [comment]
PRがマージされたためクローズ

**Comment by opst-fujimoto** [comment]
#253 で、stagingにmergeされたのでOKとみなす
masterにはmergeされていないけど。

**Comment by opsttan** [comment]
masterへのマージは、昼食か朝食のマージタイミングにあわせてやる予定です。
