### ISSUE TITLE
2016.10.11 breakfast stagingからmasterにマージして、release

### ISSUE THREAD

**Issue by opsttan** [opst-fujimoto/my-site-github#239]
## 関連チケット
- connect #235 

## マージ基準
- [x] 本日の朝食がorigin/stagingに反映されていること

https://staging-my-site-github.herokuapp.com/breakfast/201610.html
※origin/stagingのブランチは消さないこと

マージ後は、GitHubでrelease/tagの設定をおこなうこと
https://github.com/opst-fujimoto/my-site-github/releases

**Comment by opsttan** [comment]
![image](https://cloud.githubusercontent.com/assets/19678705/19257148/42756e14-8fa8-11e6-94c8-81e866e15412.png)
タグを設定しました。

**Comment by opst-ueda** [comment]
おつかれさまでした
[![LGTM](https://lgtm.in/p/wWLCnAx8q)](https://lgtm.in/i/wWLCnAx8q)
