### ISSUE TITLE
ebigcomic4のLP(Landing Page)に関するブランチを作成する

### ISSUE THREAD

**Issue by opst-fujimoto** [opst-fujimoto/my-site-github#301]
v1.6.1 をベースに、ebigcomic4 ブランチを作成する

**Comment by matsuo-y** [comment]
https://github.com/opst-fujimoto/my-site-github/tree/ebigcomic4
下記コマンドでv1.6.1からebigcomic4ブランチを作成しました
git checkout -b "ebigcomic4" refs/tags/v1.6.1

**Comment by opst-fujimoto** [comment]
https://github.com/opst-fujimoto/my-site-github/commits/ebigcomic4

できてるのでclose
