### ISSUE TITLE
/ebigcomic4/index.html において、PageSpeedの[Remove query strings from static resources]スコアをBからAに改善できる

### ISSUE THREAD

**Issue by opst-fujimoto** [opst-fujimoto/my-site-github#303]
## 事象

https://gtmetrix.com/reports/opst-fujimoto.github.io/IN3mXCuo

の結果、PageSpeedのスコアがFである。

特に、評価項目「Remove query strings from static resources」が GRADE: B であり、

> Resources with a "?" in the URL are not cached by some proxy caching servers. Remove the query string and encode the parameters into the URL for the following resources:

と指摘されている。

## 対策

- mainvisual_s.jpg へのリンクに付与している `?YMD` を削除する

## 判定基準

-  [ ] PageSpeedの評価項目[Remove query strings from static resources]が GRADE: A になること

**Comment by gonomk** [comment]
masterへのマージが完了したので、チケットをクローズします。
