### ISSUE TITLE
git config -l の結果を確認し、githubへの接続方法を確認する

### ISSUE THREAD

**Issue by opst-fujimoto** [opst-fujimoto/my-site-github#338]
## git@github.comに接続しているか？

```
git config -l
```
の結果、

```
remote.origin.url=git@github.com:opst-fujimoto/my-site-github.git
```

の1行が出力されていることを確認する

このissueに各自、コメントしてください。

- [x] 松尾
- [x] 郷野
- <del> [ ] 山崎 </del>
- [x] 土井
- [x] 上田
- [x] 譚
- [x] 馮
- [x] 中村
- [x] 高倉
- [x] 姜

**Comment by opst-ueda** [comment]
上田は問題なさそうです
![image](https://cloud.githubusercontent.com/assets/19680523/19501262/0e5ae838-95df-11e6-8e1b-b8a634b66ac8.png)

**Comment by opsttan** [comment]
譚も出力されています
![image](https://cloud.githubusercontent.com/assets/19678705/19501422/7f72f6ea-95e0-11e6-9212-07cf6bb4461a.png)

**Comment by opst-fuukei** [comment]
馮は問題なさそうです。
![image](https://cloud.githubusercontent.com/assets/21210783/19501497/16c09e62-95e1-11e6-97c4-ed9b955d3910.png)

**Comment by gonomk** [comment]
郷野も出力されています。

<img src="https://cloud.githubusercontent.com/assets/21594803/19501867/cb307fb4-95e3-11e6-9661-30562838989d.png" width="320px">

**Comment by takakura-s** [comment]
![image](https://cloud.githubusercontent.com/assets/13266469/19502272/bfbcd7b0-95e6-11e6-9356-7e1f3c35e887.png)
sshで接続しています。

**Comment by matsuo-y** [comment]
SSHで接続しています。
![image](https://cloud.githubusercontent.com/assets/8816337/19503427/71525f70-95ee-11e6-9d36-39ef4498c965.png)

**Comment by jiangheqing** [comment]
SSHで接続してます。

![image](https://cloud.githubusercontent.com/assets/22759025/19511551/9cc951a2-9622-11e6-8a02-14e3a96177ae.png)

**Comment by opstnakamura** [comment]
![image](https://cloud.githubusercontent.com/assets/17038019/19512854/df40efa8-9628-11e6-80d7-44f21fdb566b.png)

お、これだとまずいのかな？

**Comment by opstnakamura** [comment]
![image](https://cloud.githubusercontent.com/assets/17038019/19513670/b5857b0e-962b-11e6-8403-de0ab5dc42f7.png)

これでOK？

**Comment by opst-fujimoto** [comment]
その設定で、git fetch できてる？

**Comment by opst-D-Take** [comment]
![github_com_pic](https://cloud.githubusercontent.com/assets/19678703/19513828/55c5d816-962c-11e6-8430-d002516b6cbc.png)

出力OKです

**Comment by opstnakamura** [comment]
どういうメリデメがあるの？

https://help.github.com/articles/which-remote-url-should-i-use/

**Comment by opstnakamura** [comment]
速さではHTTPSのほうがよいみたい。

http://tech.nitoyon.com/ja/blog/2013/01/11/github-clone-http/

**Comment by opst-fujimoto** [comment]
https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/

2段階認証は、SSHじゃなくて、HTTPSを使っている人向けに認証を強化する手段なのか。

まあ、いずれにせよ、パスワードを入力するプロセスを省いて、SSH使いましょう　と思ってます。
